global:

rule_files: ["/etc/prometheus/rules.yml"]

alerting:
  alertmanagers:
  - static_configs: 
    - targets: ['prometheusalerting:9093']
    
    

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090', "sensorservice", "cooksessionservice"]
