version: "3.9"
services:
  sensorservice:
    build: 
      context: ../
      dockerfile: ./SensorService/Dockerfile
    ports:
      - "5000:80"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - SERIAL_PORT=/dev/tty/ACM0
      - SERIAL_BAUD=9600
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: "always"
  pidservice:
    build: 
      context: ../
      dockerfile: ./PidService/Dockerfile
    ports:
      - "5001:80"
    restart: "always"
  cooksessionservice:
    build: 
      context: ../
      dockerfile: ./CookSessionService/Dockerfile
    ports:
      - "5002:80"
    restart: "always"
  cooksessionworker:
    build: 
      context: ../
      dockerfile: ./CookSessionWorker/Dockerfile
    restart: "always"
  fancontroller:
    build: 
      context: ../
      dockerfile: ./FanController/Dockerfile
    ports:
      - "5003:80"
    environment:
      - TP_LINK_HOST=192.168.1.133
    restart: "always"
  prometheus:
    image: prom/prometheus
    ports:
     - "9090:9090" 
    volumes:
     - "./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml" 
     - "./Prometheus/rules.yml:/etc/prometheus/rules.yml" 
    restart: "always"
  prometheusalerting:
    image: prom/alertmanager
    ports:
     - "9093:9093" 
    volumes:
     - "./Prometheus/prometheus_alerts.yml:/etc/alertmanager/alertmanager.yml" 
    restart: "always"
